-- SMElink initial database schema
-- Run through Supabase migrations or paste into the SQL editor once.

create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.businesses (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  sector text not null check (sector in ('retail', 'wholesale', 'services', 'manufacturing', 'hospitality', 'other')),
  team_size text not null default 'just_me' check (team_size in ('just_me', '2_5', '6_20', 'more_than_20')),
  sales_mode text not null default 'walk_in' check (sales_mode in ('walk_in', 'orders', 'both')),
  primary_needs text[] not null default array['sales', 'inventory', 'expenses', 'reports']::text[]
    check (primary_needs <@ array['sales', 'inventory', 'orders', 'expenses', 'customers', 'reports']::text[]),
  tracks_inventory boolean not null default true,
  phone text,
  location text,
  currency char(3) not null default 'USD',
  default_stock_threshold numeric(12, 3) not null default 5 check (default_stock_threshold >= 0),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.business_members (
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'staff')),
  status text not null default 'active' check (status in ('active', 'inactive')),
  joined_at timestamptz not null default now(),
  primary key (business_id, user_id)
);

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 120),
  phone text,
  email text,
  notes text,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 140),
  sku text,
  barcode text,
  category text,
  product_type text not null default 'stocked' check (product_type in ('stocked', 'service')),
  unit text not null default 'item' check (char_length(unit) between 1 and 30),
  pack_size numeric(12, 3) not null default 1 check (pack_size > 0),
  cost_price numeric(14, 2) not null default 0 check (cost_price >= 0),
  selling_price numeric(14, 2) not null default 0 check (selling_price >= 0),
  reorder_level numeric(12, 3) not null default 0 check (reorder_level >= 0),
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (business_id, sku)
);

create unique index products_business_barcode_idx
  on public.products(business_id, barcode)
  where barcode is not null;

create table public.sales (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  sale_number bigint generated by default as identity,
  customer_id uuid references public.customers(id) on delete set null,
  order_id uuid,
  status text not null default 'draft' check (status in ('draft', 'completed', 'cancelled')),
  payment_method text not null default 'cash' check (payment_method in ('cash', 'ecocash', 'bank_transfer', 'card', 'other')),
  notes text,
  subtotal numeric(14, 2) not null default 0 check (subtotal >= 0),
  total numeric(14, 2) not null default 0 check (total >= 0),
  completed_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, sale_number)
);

create table public.sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity numeric(12, 3) not null check (quantity > 0),
  unit_price numeric(14, 2) not null check (unit_price >= 0),
  line_total numeric(14, 2) generated always as (round(quantity * unit_price, 2)) stored,
  created_at timestamptz not null default now()
);

create table public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  product_id uuid not null references public.products(id),
  sale_id uuid references public.sales(id) on delete restrict,
  movement_type text not null check (
    movement_type in (
      'opening_stock',
      'stock_received',
      'sale',
      'adjustment',
      'damaged',
      'customer_return'
    )
  ),
  quantity_change numeric(12, 3) not null check (quantity_change <> 0),
  note text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table public.expense_categories (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  unique (business_id, name)
);

create table public.expenses (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  category_id uuid references public.expense_categories(id) on delete set null,
  description text not null check (char_length(description) between 2 and 180),
  amount numeric(14, 2) not null check (amount > 0),
  payment_method text not null default 'cash' check (payment_method in ('cash', 'ecocash', 'bank_transfer', 'card', 'other')),
  expense_date date not null default current_date,
  reference text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  order_number bigint generated by default as identity,
  customer_id uuid not null references public.customers(id),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  expected_date date,
  notes text,
  subtotal numeric(14, 2) not null default 0 check (subtotal >= 0),
  total numeric(14, 2) not null default 0 check (total >= 0),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, order_number)
);

alter table public.sales
  add constraint sales_order_id_fkey
  foreign key (order_id) references public.orders(id) on delete set null;

create unique index sales_one_per_order_idx
  on public.sales(order_id)
  where order_id is not null;

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id),
  quantity numeric(12, 3) not null check (quantity > 0),
  unit_price numeric(14, 2) not null check (unit_price >= 0),
  line_total numeric(14, 2) generated always as (round(quantity * unit_price, 2)) stored,
  created_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  notification_type text not null check (notification_type in ('low_stock', 'order', 'system')),
  title text not null,
  message text not null,
  entity_type text,
  entity_id uuid,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index business_members_user_idx on public.business_members(user_id);
create index customers_business_idx on public.customers(business_id);
create index products_business_idx on public.products(business_id);
create index sales_business_date_idx on public.sales(business_id, created_at desc);
create index sale_items_sale_idx on public.sale_items(sale_id);
create index inventory_product_date_idx on public.inventory_movements(product_id, created_at desc);
create index inventory_business_date_idx on public.inventory_movements(business_id, created_at desc);
create index expenses_business_date_idx on public.expenses(business_id, expense_date desc);
create index orders_business_date_idx on public.orders(business_id, created_at desc);
create index order_items_order_idx on public.order_items(order_id);
create index notifications_user_date_idx on public.notifications(user_id, created_at desc);
create unique index notifications_one_open_entity_idx
  on public.notifications(business_id, notification_type, entity_type, entity_id)
  where read_at is null and entity_id is not null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_created_by()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.created_by = auth.uid();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();
create trigger businesses_set_updated_at before update on public.businesses
for each row execute function public.set_updated_at();
create trigger customers_set_updated_at before update on public.customers
for each row execute function public.set_updated_at();
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();
create trigger sales_set_updated_at before update on public.sales
for each row execute function public.set_updated_at();
create trigger expenses_set_updated_at before update on public.expenses
for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();
create trigger sales_set_created_by before insert on public.sales
for each row execute function public.set_created_by();
create trigger inventory_set_created_by before insert on public.inventory_movements
for each row execute function public.set_created_by();
create trigger expenses_set_created_by before insert on public.expenses
for each row execute function public.set_created_by();
create trigger orders_set_created_by before insert on public.orders
for each row execute function public.set_created_by();

create or replace function public.update_low_stock_notification()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  product_record public.products%rowtype;
  stock_on_hand numeric(12, 3);
begin
  select * into product_record
  from public.products
  where id = new.product_id;

  if product_record.product_type <> 'stocked' then
    return new;
  end if;

  select coalesce(sum(quantity_change), 0)
  into stock_on_hand
  from public.inventory_movements
  where product_id = new.product_id;

  if stock_on_hand <= product_record.reorder_level then
    insert into public.notifications (
      business_id, notification_type, title, message, entity_type, entity_id
    )
    values (
      product_record.business_id,
      'low_stock',
      'Low stock: ' || product_record.name,
      stock_on_hand || ' ' || product_record.unit ||
        ' remaining. Your restock level is ' || product_record.reorder_level || '.',
      'product',
      product_record.id
    )
    on conflict (business_id, notification_type, entity_type, entity_id)
      where read_at is null and entity_id is not null
    do update set
      title = excluded.title,
      message = excluded.message,
      created_at = now();
  else
    update public.notifications
    set read_at = now()
    where business_id = product_record.business_id
      and notification_type = 'low_stock'
      and entity_type = 'product'
      and entity_id = product_record.id
      and read_at is null;
  end if;

  return new;
end;
$$;

create trigger inventory_update_low_stock_notification
after insert on public.inventory_movements
for each row execute function public.update_low_stock_notification();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, nullif(new.raw_user_meta_data ->> 'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.is_business_member(target_business_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.business_members
    where business_id = target_business_id
      and user_id = auth.uid()
      and status = 'active'
  );
$$;

create or replace function public.is_business_owner(target_business_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.business_members
    where business_id = target_business_id
      and user_id = auth.uid()
      and role = 'owner'
      and status = 'active'
  );
$$;

create or replace function public.create_business(
  business_name text,
  business_sector text,
  business_phone text default null,
  business_location text default null,
  business_currency text default 'USD',
  business_team_size text default 'just_me',
  business_sales_mode text default 'walk_in',
  business_needs text[] default array['sales', 'inventory', 'expenses', 'reports']::text[],
  business_tracks_inventory boolean default true
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  new_business_id uuid;
  category_name text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  insert into public.businesses (
    name, sector, phone, location, currency, team_size, sales_mode,
    primary_needs, tracks_inventory, created_by
  )
  values (
    trim(business_name),
    business_sector,
    nullif(trim(business_phone), ''),
    nullif(trim(business_location), ''),
    upper(business_currency),
    business_team_size,
    business_sales_mode,
    business_needs,
    business_tracks_inventory,
    auth.uid()
  )
  returning id into new_business_id;

  insert into public.business_members (business_id, user_id, role)
  values (new_business_id, auth.uid(), 'owner');

  foreach category_name in array array[
    'Stock purchases', 'Transport', 'Utilities', 'Rent', 'Supplies', 'Other'
  ]
  loop
    insert into public.expense_categories (business_id, name, is_system)
    values (new_business_id, category_name, true);
  end loop;

  return new_business_id;
end;
$$;

create or replace view public.product_stock
with (security_invoker = true)
as
select
  p.id,
  p.business_id,
  p.name,
  p.sku,
  p.barcode,
  p.category,
  p.product_type,
  p.unit,
  p.pack_size,
  p.cost_price,
  p.selling_price,
  p.reorder_level,
  p.is_archived,
  coalesce(sum(m.quantity_change), 0)::numeric(12, 3) as quantity_on_hand
from public.products p
left join public.inventory_movements m on m.product_id = p.id
group by p.id;

create or replace function public.complete_sale(target_sale_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_sale public.sales%rowtype;
  item record;
  calculated_total numeric(14, 2);
  available_stock numeric(12, 3);
begin
  select * into target_sale
  from public.sales
  where id = target_sale_id
  for update;

  if target_sale.id is null or not public.is_business_member(target_sale.business_id) then
    raise exception 'Sale not found';
  end if;

  if target_sale.status <> 'draft' then
    raise exception 'Only a draft sale can be completed';
  end if;

  if not exists (select 1 from public.sale_items where sale_id = target_sale_id) then
    raise exception 'A sale must contain at least one item';
  end if;

  for item in
    select si.product_id, si.quantity, p.business_id, p.name, p.product_type
    from public.sale_items si
    join public.products p on p.id = si.product_id
    where si.sale_id = target_sale_id
    for update of p
  loop
    if item.business_id <> target_sale.business_id then
      raise exception 'A sale item belongs to another business';
    end if;

    if item.product_type = 'stocked' then
      select coalesce(sum(quantity_change), 0)
      into available_stock
      from public.inventory_movements
      where product_id = item.product_id;

      if available_stock < item.quantity then
        raise exception 'Not enough stock for %', item.name;
      end if;
    end if;
  end loop;

  select round(sum(line_total), 2)
  into calculated_total
  from public.sale_items
  where sale_id = target_sale_id;

  insert into public.inventory_movements (
    business_id, product_id, sale_id, movement_type,
    quantity_change, note, created_by
  )
  select
    target_sale.business_id,
    si.product_id,
    target_sale_id,
    'sale',
    -si.quantity,
    'Completed sale',
    auth.uid()
  from public.sale_items si
  join public.products p on p.id = si.product_id
  where si.sale_id = target_sale_id
    and p.product_type = 'stocked';

  update public.sales
  set
    subtotal = calculated_total,
    total = calculated_total,
    status = 'completed',
    completed_at = now()
  where id = target_sale_id;
end;
$$;

create or replace function public.convert_order_to_sale(
  target_order_id uuid,
  selected_payment_method text default 'cash'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_order public.orders%rowtype;
  new_sale_id uuid;
begin
  select * into target_order
  from public.orders
  where id = target_order_id
  for update;

  if target_order.id is null or not public.is_business_member(target_order.business_id) then
    raise exception 'Order not found';
  end if;

  if target_order.status not in ('pending', 'confirmed') then
    raise exception 'Only a pending or confirmed order can be converted';
  end if;

  if exists (select 1 from public.sales where order_id = target_order_id) then
    raise exception 'This order has already been converted';
  end if;

  insert into public.sales (
    business_id, customer_id, order_id, payment_method, created_by
  )
  values (
    target_order.business_id,
    target_order.customer_id,
    target_order.id,
    selected_payment_method,
    auth.uid()
  )
  returning id into new_sale_id;

  insert into public.sale_items (sale_id, product_id, quantity, unit_price)
  select new_sale_id, product_id, quantity, unit_price
  from public.order_items
  where order_id = target_order_id;

  perform public.complete_sale(new_sale_id);

  update public.orders
  set status = 'completed'
  where id = target_order_id;

  return new_sale_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.businesses enable row level security;
alter table public.business_members enable row level security;
alter table public.customers enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.expense_categories enable row level security;
alter table public.expenses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.notifications enable row level security;

create policy "profiles_select_own" on public.profiles
for select using (id = auth.uid());
create policy "profiles_update_own" on public.profiles
for update using (id = auth.uid()) with check (id = auth.uid());

create policy "businesses_select_member" on public.businesses
for select using (public.is_business_member(id));
create policy "businesses_update_owner" on public.businesses
for update using (public.is_business_owner(id)) with check (public.is_business_owner(id));

create policy "members_select_member" on public.business_members
for select using (public.is_business_member(business_id));
create policy "members_insert_owner" on public.business_members
for insert with check (public.is_business_owner(business_id));
create policy "members_update_owner" on public.business_members
for update using (public.is_business_owner(business_id)) with check (public.is_business_owner(business_id));
create policy "members_delete_owner" on public.business_members
for delete using (public.is_business_owner(business_id) and user_id <> auth.uid());

create policy "customers_member_all" on public.customers
for all using (public.is_business_member(business_id))
with check (public.is_business_member(business_id));

create policy "products_member_all" on public.products
for all using (public.is_business_member(business_id))
with check (public.is_business_member(business_id));

create policy "sales_member_all" on public.sales
for all using (public.is_business_member(business_id))
with check (public.is_business_member(business_id));

create policy "sale_items_member_select" on public.sale_items
for select using (
  exists (
    select 1 from public.sales
    where sales.id = sale_items.sale_id
      and public.is_business_member(sales.business_id)
  )
);
create policy "sale_items_member_insert" on public.sale_items
for insert with check (
  exists (
    select 1 from public.sales
    where sales.id = sale_items.sale_id
      and sales.status = 'draft'
      and public.is_business_member(sales.business_id)
  )
);
create policy "sale_items_member_update" on public.sale_items
for update using (
  exists (
    select 1 from public.sales
    where sales.id = sale_items.sale_id
      and sales.status = 'draft'
      and public.is_business_member(sales.business_id)
  )
);
create policy "sale_items_member_delete" on public.sale_items
for delete using (
  exists (
    select 1 from public.sales
    where sales.id = sale_items.sale_id
      and sales.status = 'draft'
      and public.is_business_member(sales.business_id)
  )
);

create policy "inventory_member_select" on public.inventory_movements
for select using (public.is_business_member(business_id));
create policy "inventory_member_insert" on public.inventory_movements
for insert with check (
  public.is_business_member(business_id)
  and movement_type <> 'sale'
);

create policy "expense_categories_member_all" on public.expense_categories
for all using (public.is_business_member(business_id))
with check (public.is_business_member(business_id));

create policy "expenses_member_all" on public.expenses
for all using (public.is_business_member(business_id))
with check (public.is_business_member(business_id));

create policy "orders_member_all" on public.orders
for all using (public.is_business_member(business_id))
with check (public.is_business_member(business_id));

create policy "order_items_member_select" on public.order_items
for select using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and public.is_business_member(orders.business_id)
  )
);
create policy "order_items_member_write" on public.order_items
for all using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.status in ('pending', 'confirmed')
      and public.is_business_member(orders.business_id)
  )
) with check (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.status in ('pending', 'confirmed')
      and public.is_business_member(orders.business_id)
  )
);

create policy "notifications_member_select" on public.notifications
for select using (
  public.is_business_member(business_id)
  and (user_id is null or user_id = auth.uid())
);
create policy "notifications_mark_read" on public.notifications
for update using (
  public.is_business_member(business_id)
  and (user_id is null or user_id = auth.uid())
) with check (
  public.is_business_member(business_id)
  and (user_id is null or user_id = auth.uid())
);

revoke all on function public.create_business(text, text, text, text, text, text, text, text[], boolean) from public;
revoke all on function public.complete_sale(uuid) from public;
revoke all on function public.convert_order_to_sale(uuid, text) from public;
grant execute on function public.create_business(text, text, text, text, text, text, text, text[], boolean) to authenticated;
grant execute on function public.complete_sale(uuid) to authenticated;
grant execute on function public.convert_order_to_sale(uuid, text) to authenticated;
