-- Service invoices: create unpaid, mark paid to record the sale.
-- Apply after 0009_services_and_customers.sql.

begin;

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  invoice_number bigint generated by default as identity,
  customer_id uuid references public.customers(id) on delete set null,
  status text not null default 'unpaid'
    check (status in ('unpaid', 'paid', 'overdue', 'lost')),
  currency char(3) not null default 'USD'
    check (currency in ('USD', 'ZIG', 'ZAR')),
  issue_date date not null default current_date,
  due_date date not null default current_date,
  notes text,
  subtotal numeric(14, 2) not null default 0 check (subtotal >= 0),
  total numeric(14, 2) not null default 0 check (total >= 0),
  sale_id uuid references public.sales(id) on delete set null,
  paid_at timestamptz,
  payment_method text
    check (
      payment_method is null
      or payment_method in ('cash', 'ecocash', 'bank_transfer', 'card', 'other')
    ),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, invoice_number)
);

create index if not exists invoices_business_id_idx
  on public.invoices(business_id);
create index if not exists invoices_status_idx
  on public.invoices(business_id, status);

create table if not exists public.invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  description text not null check (char_length(description) between 1 and 200),
  quantity numeric(12, 3) not null check (quantity > 0),
  unit_price numeric(14, 2) not null check (unit_price >= 0),
  line_total numeric(14, 2) generated always as (round(quantity * unit_price, 2)) stored,
  created_at timestamptz not null default now()
);

create index if not exists invoice_items_invoice_id_idx
  on public.invoice_items(invoice_id);

alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;

drop policy if exists "invoices_member_all" on public.invoices;
create policy "invoices_member_all" on public.invoices
for all using (public.is_business_member(business_id))
with check (public.is_business_member(business_id));

drop policy if exists "invoice_items_member_all" on public.invoice_items;
create policy "invoice_items_member_all" on public.invoice_items
for all using (
  exists (
    select 1 from public.invoices i
    where i.id = invoice_id
      and public.is_business_member(i.business_id)
  )
)
with check (
  exists (
    select 1 from public.invoices i
    where i.id = invoice_id
      and public.is_business_member(i.business_id)
  )
);

drop trigger if exists invoices_set_created_by on public.invoices;
create trigger invoices_set_created_by before insert on public.invoices
for each row execute function public.set_created_by();

drop trigger if exists invoices_set_updated_at on public.invoices;
create trigger invoices_set_updated_at before update on public.invoices
for each row execute function public.set_updated_at();

-- Mark unpaid/overdue invoice as paid and create a completed sale.
create or replace function public.mark_invoice_paid(
  target_invoice_id uuid,
  selected_payment_method text default 'cash'
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.invoices%rowtype;
  new_sale_id uuid;
  calculated_total numeric(14, 2);
begin
  select * into target
  from public.invoices
  where id = target_invoice_id
  for update;

  if target.id is null or not public.is_business_member(target.business_id) then
    raise exception 'Invoice not found';
  end if;

  if target.status not in ('unpaid', 'overdue') then
    raise exception 'Only unpaid or overdue invoices can be marked paid';
  end if;

  if target.sale_id is not null then
    raise exception 'This invoice is already linked to a sale';
  end if;

  if not exists (
    select 1 from public.invoice_items where invoice_id = target_invoice_id
  ) then
    raise exception 'Invoice has no line items';
  end if;

  if selected_payment_method is null
    or selected_payment_method not in ('cash', 'ecocash', 'bank_transfer', 'card', 'other')
  then
    raise exception 'Choose a payment method';
  end if;

  select round(sum(line_total), 2)
  into calculated_total
  from public.invoice_items
  where invoice_id = target_invoice_id;

  insert into public.sales (
    business_id,
    customer_id,
    payment_method,
    currency,
    notes,
    created_by
  )
  values (
    target.business_id,
    target.customer_id,
    selected_payment_method,
    target.currency,
    target.notes,
    auth.uid()
  )
  returning id into new_sale_id;

  insert into public.sale_items (sale_id, product_id, quantity, unit_price)
  select
    new_sale_id,
    product_id,
    quantity,
    unit_price
  from public.invoice_items
  where invoice_id = target_invoice_id
    and product_id is not null;

  if not exists (select 1 from public.sale_items where sale_id = new_sale_id) then
    raise exception 'Invoice lines must reference a service';
  end if;

  perform public.complete_sale(new_sale_id);

  update public.invoices
  set
    status = 'paid',
    sale_id = new_sale_id,
    paid_at = now(),
    payment_method = selected_payment_method,
    subtotal = calculated_total,
    total = calculated_total,
    updated_at = now()
  where id = target_invoice_id;

  return new_sale_id;
end;
$$;

revoke all on function public.mark_invoice_paid(uuid, text) from public;
grant execute on function public.mark_invoice_paid(uuid, text) to authenticated;

-- Flip unpaid past due_date to overdue (safe to call often).
create or replace function public.refresh_overdue_invoices(
  target_business_id uuid default null
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated_count integer;
begin
  update public.invoices i
  set status = 'overdue', updated_at = now()
  where i.status = 'unpaid'
    and i.due_date < current_date
    and public.is_business_member(i.business_id)
    and (target_business_id is null or i.business_id = target_business_id);

  get diagnostics updated_count = row_count;
  return updated_count;
end;
$$;

revoke all on function public.refresh_overdue_invoices(uuid) from public;
grant execute on function public.refresh_overdue_invoices(uuid) to authenticated;

commit;
